config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'application#hello_world'

  resources :users do
    member do
      get :following, :followers
    end
    collection do
      get :admins
    end
  end
  resources :posts
  resources :admin
  get 'login', to:'sessions#new'
  post 'login', to: 'sessions#create'
  #to fix this!!
  delete 'logout', to: 'sessions#destroy'
  get 'make_admin', to: 'users#make_admin'
  post 'make admin', to: 'users#make_admin'
  #get 'users/:id/following',to: 'users#following'
  #get 'users/:id/followers',to: 'users#followers'
  #get 'create', to:'posts#create'
  #get 'users', to: 'users#index'
  #get 'users/new', to:'users#new'
  #get 'users/:id', to: 'users#show'
  #post 'users', to: 'users#create'
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/application_controller.rb
class ApplicationController < ActionController::Base
  def helloblabla
    render html: 'Hello, salut'
  end
  
  def alta_ruta
    # render html: 'Ai intrat pe alta ruta!'
  end
    def index
    #o variabila fara @ este vizibila doar in functie
    #o variabila cu @este vizibila si in afara functiei
    @user=User.fisrt
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :description, presence: true,length: {maximum: 120}
  validates :user_id,presence: true
  validates :title, presence: true 
  default_scope ->{order(created_at: :desc)}
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower,class_name: 'User'
    belongs_to :followed,class_name: 'User'
end

app/models/session.rb
class Session < ActiveRecord::Base
    validates :email,presence: true
    has_secure_password
  end

app/models/user.rb
class User < ApplicationRecord
validates :name, presence: true
validates :email,presence: true
#validates :age,presence: true
#validates :age, comparison: { greater_than: 0 }
#validates :age, comparison: { less_than: 100 }
#validates :gender,presence: true
#validates :phone_number,presence: true
has_secure_password
has_many :posts, dependent: :destroy
has_many :follower_relationships, class_name: 'Relationship',foreign_key: 'follower_id',dependent: :destroy
has_many :followed_relationships, class_name: 'Relationship',foreign_key: 'followed_id',dependent: :destroy
has_many :following,through: :follower_relationships,source: :followed
has_many :followers,through: :followed_relationships,source: :follower
def follow(other_user)
    following << other_user
end
def unfollow(other_user)
    following.delete(other_user)
end
def following?(other_user)
following.include?(other_user)
end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
    def show
        @user = User.where(admin: true).first
        if !current_user.admin?
            redirect_to '/users/'
        end
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
include SessionsHelper
    def hello_world
        if logged_in?
        redirect_to users_path
        else
            redirect_to login_path
        end
    end
    def admin_user
        redirect_to(root_url) unless current_user.admin?
    end
    def check_user
        redirect_to login_path unless logged_in?
    end
    def check_user_post
        redirect_to user_path unless current_user
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :check_user,only:[:create,:edit,:update]
    def index
        @posts=Post.all
    end
    def show
        @post = Post.where(id: params[:id]).first
    end
    def new
      @post=Post.new
    end
    def create
        @post=current_user.posts.new(post_params)
        #@post.user_id=current_user.id
        if @post.save
            redirect_to user_path(current_user)
        else
            @user=current_user
            @posts=@user.posts.paginate(page: params[:page],per_page: 5)
            render 'users/show',status: 422
        end
    end
    def edit
        @post = Post.find(params[:id])
        if @post.user_id!=current_user.id 
          render 'posts/show',status:422
        end
    end
    
      def update
        @post = Post.find(params[:id])
           if @post.update(post_params) && @post.user_id==current_user.id 
              redirect_to user_path(current_user)
           else
              render 'posts/edit', status: 422
           end
      end
    
      private
    
    def post_params
        params.require(:post).permit(:title,:description)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
       if logged_in?
        redirect_to '/users/'
       end
    end
    def create
        user=User.find_by(email: params['email'])
        if user.present? && user.authenticate(params['password'])
            log_in(user)
            redirect_to user_path(user)
        else
            flash[:error]='Invalid credentials'
            redirect_to '/login'
        end
    end
    def destroy
        log_out
        redirect_to login_path
    end
end

app/controllers/shared_controller.rb
class SharedController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :check_user,only: [:index, :show, :destroy]
    before_action :admin_user,only: [:destroy,:make_admin]
    before_action :check_delete_user,only:[:destroy]
    def index
        # o variabila fara @ este vizibila doar in functie
        # o variabila cu @ este vizibila si in afara functiei
        @users = User.all
    end

    def show
        @user = User.where(id: params[:id]).first
        if @user.present?
            @posts = @user.posts.paginate(page: params[:page], per_page: 5)
            @post = Post.new
          end
    end
    def new
    @user=User.new
    end
    def create
    @user = User.new(user_params)
    if @user.save
        flash[:succes]="User adaugat"
        log_in(@user)
        redirect_to user_path(@user)
          else
            render 'users/new' ,status: 422
    end
    end
    def make_admin
        @user=User.find(params[:id])
        @user.update(admin:true)
    end
    def check_delete_user
        @user=User.find(params[:id])
        if @user.name[0]!='A'
            redirect_to users_path
            flash[:error]='Nu incepe cu A'
        end
    end
    def destroy
        @user=User.find(params[:id])
        #if @user.name[0]=='A'
            @user.destroy
            flash[:succes]='Userul a fost sters'
            redirect_to users_path
        #else
         #   flash[:error]='Nu incepe cu A'
          #  redirect_to users_path
        #end
    end
    def following
        @title='Following'
        @user=User.find(params[:id])
        @users=@user.following.paginate(page:params[:page],per_page: 1)
        render 'show_follow',status: 422
    end
    def followers
        @title='Followers'
        @user=User.find(params[:id])
        @users=@user.followers.paginate(page:params[:page],per_page: 1)
        render 'show_follow',status: 422
    end
    private
    def user_params
        params.require(:user).permit(:name,:email,:password,:phone_number,:gender,:age,:admin)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id]=user.id
    end
    def current_user
        if session[:user_id].present?
            User.find_by(id:session[:user_id])
        end
    end
    def log_out
        session[:user_id]=nil
    end
    def logged_in?
        current_user.present?
    end
    # return true if given user is the current user
    def current_user?(user)
        current_user==user
    end
end

app/helpers/shared_helper.rb
module SharedHelper
end

app/views/admin/show.html.erb
<h1>Statistics</h1>
<div>
<%=link_to('Back to users','/users') %>
</div>
<div class="row">
   <div class="col-md-4">
         <% if @user.nil? %>
               Nu exista admin
         <% else %>
         <div class="card user-card">
         <div class="card-body">
           <h5 class="card-title"><%='Number of users'%><br></h5>
           <p class="card-text">
           total: <%= User.count %><br>
           admins: <%= User.where(admin:true).count %>
       </div>
       </div>
         <% end %>
   </div>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Twitter</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Users', '/users', class: 'nav-link' %>
        </li>
        <%= link_to 'Posts', '/posts', class: 'nav-link' %>
      </ul>
      <% if logged_in? %>
      <div class="navbar-nav pull-right">
      <%= link_to 'Logout', logout_path, data:{turbo_method: :delete}, class: 'nav-link btn btn-link' %>
      </div>
      <div class="navbar-nav pull-right">
      <%=link_to current_user.name,user_path(current_user),class: 'nav-link' %>
      </div>
      <% else %>
      <div class="navbar-nav pull-right">
            <%= link_to 'Sign Up', new_user_path, class: 'nav-link' %>
      </div>
      <div class="navbar-nav pull-right">
            <%= link_to 'Login', '/login', class: 'nav-link' %>
      </div>
      <% end %>
    <div>
    <div>
  </div>
</nav>
<div class="p-2">
<%= yield %>
</div>
  </body>
</html>

app/views/posts/_create.html.erb
<%= render partial: 'shared/error_messages', locals: { obj: @post } %>
<%= form_with model: @post do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: 'Insert title...' %>
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control', placeholder: 'Insert content...' %>
    <%= f.submit 'Post', class: 'btn btn-primary mt-2' %>
    <% end %>

app/views/posts/_pagination.html.erb
<%= will_paginate(@posts, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: "pagination bg-transparent") %>

app/views/posts/_post.html.erb
<div class="card user-card">
  <div class="card-body">
    <h5 class="card-title"><%=link_to(post.title, post)%><br></h5>
    <p class="card-text">
    description <%= post.description %><br>
    Posted by <%= link_to post.user.name, post.user %> <%= time_ago_in_words(post.updated_at) %> ago.
    </p>
    <% if post.user_id==current_user.id %>
    <%= link_to 'Edit', edit_post_path(post) %>
    <% end %>
    </div>
</div>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= form_with model: @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control', placeholder: 'Insert title...' %>
  <%= f.label :description %>
  <%= f.text_field :description, class: 'form-control', placeholder: 'Insert content...' %>
  <%= f.submit 'Edit', class: 'btn btn-primary mt-2' %>
<% end %>

app/views/posts/index.html.erb
<h1> Posts</h1>
<% @post=Post.new %>
<%= render partial: 'posts/create' %>
<ul>
	<% @posts=@posts.paginate(page:params[:page],per_page: 10)%>
	<% @posts.each do |post| %>
	<li >
        <%= render post%>	
		</li>
	<% end %>
	<%= render partial: 'posts/pagination' %>
</ul>

app/views/posts/show.html.erb
<div>
<%=link_to('Back to posts','/posts') %>
</div>
<% if @post.nil? %>
   Nu exista posts
<% else %>
<%= render @post%>
<% end %>

app/views/shared/_error_messages.html.erb
<% if obj.errors.present? %>
  <div class="alert alert-danger">
    <% obj.errors.full_messages.each do |error| %>
      <div>
        <%= error %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<div class='row'>
<div class="col-md-6-lg-3 col-sm-6 border-right text-center">
<a href="<%= following_user_path(@user) %>">
<strong><%= @user.following.count %></strong><br>
<strong>Following</strong>
</a>
</div>
<div class="col-md-6-lg-3 col-sm-6 border-right text-center">
<a href="<%= followers_user_path(@user) %>">
<strong><%= @user.followers.count %></strong><br>
<strong>Followers</strong>
</a>
</div>
</div>

app/views/users/_user.html.erb
<div class="card user-card">
  <div class="card-body">
    <h5 class="card-title"><%=link_to(user.name,"/users/#{user.id}")%><br></h5>
    <p class="card-text">email: <%= user.email %><br>
age: <%= user.age %><br>
gender: <%= user.gender %><br>
phone_number: <%=user.phone_number %></p>
<% if current_user.admin? && !current_user?(user) && !user.admin%>
<%= link_to 'delete', user, data: {turbo_method: :delete,turbo_confirm:'Are you sure?'} %><br>
<% end %>
<% if current_user.admin? && !current_user?(user) && !user.admin%>
<%= link_to 'make admin',user,action: :make_admin,turbo_method: :post%>
<% end %>
</div>
</div>

app/views/users/index.html.erb
<h1> Users </h1>
<% if flash[:error] %>
<div class="alert alert-danger" role="alert">
<%= flash[:error]%>
</div>
<% end %>
<% if flash[:succes] %>
#culoarea verde ??
<div class="alert alert" role="alert">
<%= flash[:succes]%>
</div>
<% end %>
<ul>
	<% @users.each do |user| %>
	<li >
        <%= render user 	%>
		<!-- <%= render partial:'user', locals:{ user: user } %> -->
				</li>
	<% end %>
</ul>

<%
=begin%>
<%  %> - doar ruleaza cod de ruby
  <%= %> - afiseaza codul de ruby
<%
=end%>

app/views/users/new.html.erb
<div class="row justify-content-center">
<div class="col-xs-12 col-sm-5">
<%= render partial: 'shared/error_messages', locals: { obj: @user } %>
<%= form_for @user do |f| %>
	<%= f.label :Name %>
	 <%= f.text_field :name , class: 'form-control'%> <br />
	 <%= f.label :Email %>
	 <%= f.email_field :email , class: 'form-control'%> <br/>
	 <%= f.label :Password %>
	 <%=f.password_field :password,class: 'form-control'%><br/>
	 <%= f.label :Age %>
	 <%= f.number_field :age , class: 'form-control'%> <br/>
	 <%= f.label :Gender %>
	 <%= f.text_field :gender , class: 'form-control'%><br/>
	 <%= f.label :Phone %>
	 <%= f.telephone_field :phone_number , class: 'form-control'%><br/>
	<%= f.submit 'Sign Up'%>
<% end %>
</div>
</div>

app/views/users/show.html.erb
<div>
<%=link_to('Back to users','/users') %>
</div>
<% if flash[:succes] %>
<div class="alert alert-success" role="alert">
<%=flash[:succes]%>
</div>
<% end %>
<div class="row">
   <div class="col-md-4">
         <% if @user.nil? %>
               Nu exista userul
         <% else %>
               <%= render @user %>
               <%= render 'shared/stats' %>
                       <% end %>
              <% if current_user.id==@user.id %>
              <%= render partial: 'posts/create' %>
              <% end %>
             </div>
             
             <% if @user.present? %>
             <div class="col-md-6">
               <h3> Posts (<%= @posts.count%>)</h3>
               <%= render @posts %>
               <%= render partial: 'posts/pagination' %>
               
             </div>
           <% end %>   
</div>

app/views/users/show_follow.html.erb
<div>
<%=link_to('Back to users','/users') %>
</div>
<div class="row">
   <div class="col-md-4">
         <% if @user.nil? %>
               Nu exista userul
         <% else %>
               <%= render @user %>
                       <% end %>
             </div>
             <% if @user.present? %>
             <div class="col-md-6">
               <h3><%= @title %></h3>
               <%= render @users %>
               <%= render partial: 'posts/pagination' %>
             </div>
           <% end %>   
</div>